name: release

on:
  push:
    tags:
      - v*

env:
  NAME: dropbox-shared-link-cli

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: cargo-index-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v1
        with:
          path: ./target
          key: cargo-build-target-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=${{ matrix.target }}
      - run: |
          zip -j ./${{ env.NAME }}-${{ matrix.target }}.zip ./target/${{ matrix.target }}/release/${{ env.NAME }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.NAME }}-${{ matrix.target }}
          path: ./${{ env.NAME }}-${{ matrix.target }}.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - run: |
          echo '${{ steps.create_release.outputs.upload_url }}' > ./upload_url
      - uses: actions/upload-artifact@v1
        with:
          name: upload_url
          path: ./upload_url
  upload:
    needs: release
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: ${{ env.NAME }}-${{ matrix.target }}
      - uses: actions/download-artifact@v1
        with:
          name: upload_url
      - id: read_url
        run: |
          echo "::set-output name=upload_url::$(cat ./upload_url/upload_url)"
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.read_url.outputs.upload_url }}
          asset_path: ./${{ env.NAME }}-${{ matrix.target }}/${{ env.NAME }}-${{ matrix.target }}.zip
          asset_name: ${{ env.NAME }}-${{ matrix.target }}.zip
          asset_content_type: application/zip
